import Head from "next/head";
import Image from "next/image";

import Box from "@material-ui/core/Box";
import Container from "@material-ui/core/Container";
import Typography from "@material-ui/core/Typography";

import Link from "components/Link";

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Le site d'Oscar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box mt={5}></Box>

      <Typography align="center" variant="h2">
        Salut!
        <br />
        Bienvenue sur le site d'<span style={{ color: "blue" }}>Oscar</span>
      </Typography>

      <Box my="15vh"></Box>

      <Typography variant="h5">
        <Link href="/video-games">Mes jeux vidéos préférés</Link>
      </Typography>
      <Box mt={1}></Box>
    </Container>
  );
}
