import Head from "next/head";
import Image from "next/image";

import Box from "@material-ui/core/Box";
import Grid from "@material-ui/core/Grid";
import Typography from "@material-ui/core/Typography";
import Container from "@material-ui/core/Container";

import Link from "components/Link";
import VideoGameCard from "components/VideoGameCard";

const games = [
  {
    name: "Jedi Fallen Order",
    description:
      "Dans Jedi Fallen Order vous incarnez le rôle de Kall un jedi ayant survécu à la purge jedi, il devra découvrir les secrets jedi.",
    image: "/video-games/star-wars-jedi-fallen-order-key-art-logo.jpg",
    url: "https://fr.wikipedia.org/wiki/Star_Wars_Jedi:_Fallen_Order",
  },
  {
    name: "Minecraft",
    description:
      "Vous êtes dans un monde cubique où vous devez survivre et tuer un dragon.",
    image: "/video-games/How-to-Fix-Minecraft-Keeps-Crashing-Windows-10.jpg",
    url: "https://fr.wikipedia.org/wiki/Minecraft",
  },
];

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Top 10 de mes jeux vidéos préférés</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box mt={1}></Box>
      <Grid container justifyContent="flex-start">
        <Grid item>
          <Typography variant="h5">
            <Link href="/">Accueil</Link>
          </Typography>
        </Grid>
      </Grid>

      <Typography align="center" variant="h2">
        Top 10 de mes jeux vidéos préférés
      </Typography>

      <Box my={5}></Box>

      <Grid container justifyContent="space-evenly">
        {games.map((game) => (
          <Grid item key={game.name}>
            <Box mx={2} my={2}>
              <VideoGameCard
                name={game.name}
                description={game.description}
                image={game.image}
                url={game.url}
              ></VideoGameCard>
            </Box>
          </Grid>
        ))}
      </Grid>
    </Container>
  );
}
